CREATE TABLE `life_hirlev` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hirlev_id` int(11) NOT NULL,
  `sendingdate` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `folder` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `analytics_source` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `analytics_medium` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu1` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu1_link` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu1_analytics` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu2` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu2_link` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu2_analytics` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu3` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu3_link` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu3_analytics` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu4` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu4_link` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `menu4_analytics` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `bp_link` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `bp_analytics` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `bp_pic` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `bp_title` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `bp_text` text COLLATE latin2_hungarian_ci NOT NULL,
  `bp_price` tinytext COLLATE latin2_hungarian_ci NOT NULL,
  `1ok` tinytext CHARACTER SET latin1,
  `1l_link` tinytext COLLATE latin2_hungarian_ci,
  `1l_analytics` tinytext COLLATE latin2_hungarian_ci,
  `1l_pic` tinytext COLLATE latin2_hungarian_ci,
  `1l_title` tinytext COLLATE latin2_hungarian_ci,
  `1l_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `1l_text` text COLLATE latin2_hungarian_ci,
  `1l_price` tinytext COLLATE latin2_hungarian_ci,
  `1r_link` tinytext COLLATE latin2_hungarian_ci,
  `1r_analytics` tinytext COLLATE latin2_hungarian_ci,
  `1r_pic` tinytext COLLATE latin2_hungarian_ci,
  `1r_title` tinytext COLLATE latin2_hungarian_ci,
  `1r_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `1r_text` text COLLATE latin2_hungarian_ci,
  `1r_price` tinytext COLLATE latin2_hungarian_ci,
  `2ok` tinytext CHARACTER SET latin1,
  `2l_link` tinytext COLLATE latin2_hungarian_ci,
  `2l_analytics` tinytext COLLATE latin2_hungarian_ci,
  `2l_pic` tinytext COLLATE latin2_hungarian_ci,
  `2l_title` tinytext COLLATE latin2_hungarian_ci,
  `2l_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `2l_text` text COLLATE latin2_hungarian_ci,
  `2l_price` tinytext COLLATE latin2_hungarian_ci,
  `2r_link` tinytext COLLATE latin2_hungarian_ci,
  `2r_analytics` tinytext COLLATE latin2_hungarian_ci,
  `2r_pic` tinytext COLLATE latin2_hungarian_ci,
  `2r_title` tinytext COLLATE latin2_hungarian_ci,
  `2r_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `2r_text` text COLLATE latin2_hungarian_ci,
  `2r_price` tinytext COLLATE latin2_hungarian_ci,
  `3ok` tinytext CHARACTER SET latin1,
  `3l_link` tinytext COLLATE latin2_hungarian_ci,
  `3l_analytics` tinytext COLLATE latin2_hungarian_ci,
  `3l_pic` tinytext COLLATE latin2_hungarian_ci,
  `3l_title` tinytext COLLATE latin2_hungarian_ci,
  `3l_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `3l_text` text COLLATE latin2_hungarian_ci,
  `3l_price` tinytext COLLATE latin2_hungarian_ci,
  `3r_link` tinytext COLLATE latin2_hungarian_ci,
  `3r_analytics` tinytext COLLATE latin2_hungarian_ci,
  `3r_pic` tinytext COLLATE latin2_hungarian_ci,
  `3r_title` tinytext COLLATE latin2_hungarian_ci,
  `3r_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `3r_text` text COLLATE latin2_hungarian_ci,
  `3r_price` tinytext COLLATE latin2_hungarian_ci,
  `4ok` tinytext CHARACTER SET latin1,
  `4l_link` tinytext COLLATE latin2_hungarian_ci,
  `4l_analytics` tinytext COLLATE latin2_hungarian_ci,
  `4l_pic` tinytext COLLATE latin2_hungarian_ci,
  `4l_title` tinytext COLLATE latin2_hungarian_ci,
  `4l_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `4l_text` text COLLATE latin2_hungarian_ci,
  `4l_price` tinytext COLLATE latin2_hungarian_ci,
  `4r_link` tinytext COLLATE latin2_hungarian_ci,
  `4r_analytics` tinytext COLLATE latin2_hungarian_ci,
  `4r_pic` tinytext COLLATE latin2_hungarian_ci,
  `4r_title` tinytext COLLATE latin2_hungarian_ci,
  `4r_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `4r_text` text COLLATE latin2_hungarian_ci,
  `4r_price` tinytext COLLATE latin2_hungarian_ci,
  `5ok` tinytext CHARACTER SET latin1,
  `5l_link` tinytext COLLATE latin2_hungarian_ci,
  `5l_analytics` tinytext COLLATE latin2_hungarian_ci,
  `5l_pic` tinytext COLLATE latin2_hungarian_ci,
  `5l_title` tinytext COLLATE latin2_hungarian_ci,
  `5l_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `5l_text` text COLLATE latin2_hungarian_ci,
  `5l_price` tinytext COLLATE latin2_hungarian_ci,
  `5r_link` tinytext COLLATE latin2_hungarian_ci,
  `5r_analytics` tinytext COLLATE latin2_hungarian_ci,
  `5r_pic` tinytext COLLATE latin2_hungarian_ci,
  `5r_title` tinytext COLLATE latin2_hungarian_ci,
  `5r_subtitle` tinytext COLLATE latin2_hungarian_ci,
  `5r_text` text COLLATE latin2_hungarian_ci,
  `5r_price` tinytext COLLATE latin2_hungarian_ci,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin2 COLLATE=latin2_hungarian_ci AUTO_INCREMENT=100 ;
